export const VARIANT_MAPPINGS = {
  'body-1': '.typo-body-1',
  'body-2': '.typo-body-2',
  'body-3': '.typo-body-3',
  'button-1': '.typo-button-1',
  'button-2': '.typo-button-2',
  'button-3': '.typo-button-3',
  'heading-1': '.typo-heading-1',
  'heading-2': '.typo-heading-2',
  'heading-3': '.typo-heading-3',
  'heading-4': '.typo-heading-4',
  'heading-5': '.typo-heading-5',
  'heading-6': '.typo-heading-6',
  'label-1': '.typo-label-1',
  'label-2': '.typo-label-2',
  'label-2-strong': '.typo-label-2-strong',
  'label-3': '.typo-label-3',
  'subtitle-1': '.typo-subtitle-1',
  'subtitle-2': '.typo-subtitle-2',
  'subtitle-3': '.typo-subtitle-3',
} as const;
